CREATE TABLE [dbo].[PRD_PRODUCT](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [nvarchar](max) NULL,
	[PRICE_UNIT] [decimal](18, 2) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

CREATE TABLE [dbo].[SL_SALE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DT_SALE] [datetime] NULL,
	[VLR_AMOUNT] [decimal](10, 2) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[SLI_SALEITEM](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[SL_ID] [int] NULL,
	[PRD_ID] [int] NULL,
	[QTD_PRD] [int] NULL,
	[VLR_SUB] [decimal](10, 2) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[SLI_SALEITEM]  WITH CHECK ADD FOREIGN KEY([PRD_ID])
REFERENCES [dbo].[PRD_PRODUCT] ([ID])
GO

ALTER TABLE [dbo].[SLI_SALEITEM]  WITH CHECK ADD FOREIGN KEY([SL_ID])
REFERENCES [dbo].[SL_SALE] ([ID])
GO
