// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TesteTecnico.Raltec01.Infra.Data.Context;

#nullable disable

namespace TesteTecnico.Raltec01.Infra.Data.Migrations
{
	[DbContext(typeof(ApplicationContext))]
	partial class ApplicationContextModelSnapshot : ModelSnapshot
	{
		protected override void BuildModel(ModelBuilder modelBuilder)
		{
#pragma warning disable 612, 618
			modelBuilder
				.HasAnnotation("ProductVersion", "7.0.11")
				.HasAnnotation("Relational:MaxIdentifierLength", 128);

			SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

			modelBuilder.Entity("TesteTecnico.Raltec01.Domain.Entities.Product", b =>
				{
					b.Property<Guid>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("uniqueidentifier");

					b.Property<string>("Name")
						.IsRequired()
						.HasColumnType("VARCHAR(100)");

					b.Property<decimal>("UnitValue")
						.HasColumnType("decimal(18,2)");

					b.HasKey("Id");

					b.ToTable("products", (string)null);
				});

			modelBuilder.Entity("TesteTecnico.Raltec01.Domain.Entities.Sale", b =>
				{
					b.Property<Guid>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("uniqueidentifier");

					b.Property<int>("CodeSale")
						.ValueGeneratedOnAdd()
						.HasColumnType("int");

					SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodeSale"));

					b.Property<DateTime>("DateAndHour")
						.ValueGeneratedOnAdd()
						.HasColumnType("datetime2")
						.HasDefaultValueSql("GETDATE()");

					b.HasKey("Id");

					b.ToTable("sales", (string)null);
				});

			modelBuilder.Entity("TesteTecnico.Raltec01.Domain.Entities.SaleItem", b =>
				{
					b.Property<Guid>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("uniqueidentifier");

					b.Property<decimal>("Discount")
						.HasColumnType("decimal(18,2)");

					b.Property<Guid>("ProductId")
						.HasColumnType("uniqueidentifier");

					b.Property<int>("Quantity")
						.ValueGeneratedOnAdd()
						.HasColumnType("int")
						.HasDefaultValue(1);

					b.Property<Guid>("SaleId")
						.HasColumnType("uniqueidentifier");

					b.Property<decimal>("Value")
						.HasColumnType("decimal(18,2)");

					b.HasKey("Id");

					b.HasIndex("ProductId");

					b.HasIndex("SaleId");

					b.ToTable("sale_items", (string)null);
				});

			modelBuilder.Entity("TesteTecnico.Raltec01.Domain.Entities.SaleItem", b =>
				{
					b.HasOne("TesteTecnico.Raltec01.Domain.Entities.Product", "Product")
						.WithMany()
						.HasForeignKey("ProductId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();

					b.HasOne("TesteTecnico.Raltec01.Domain.Entities.Sale", "Sale")
						.WithMany("Items")
						.HasForeignKey("SaleId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();

					b.Navigation("Product");

					b.Navigation("Sale");
				});

			modelBuilder.Entity("TesteTecnico.Raltec01.Domain.Entities.Sale", b =>
				{
					b.Navigation("Items");
				});
#pragma warning restore 612, 618
		}
	}
}
